require "game/gameObject/loader/ObjectGroup"
require "game/gameObject/loader/EffectGroup"
require "game/gameObject/loader/ObjectLoader"
require "game/gameObject/loader/EndlessLoader"
require "game/gameObject/loader/MemeryPool"
require "game/gameObject/loader/PoolFunc"
require "game/gameObject/loader/HolyLoader"
