-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('common_pb')


local SERVERINFO = protobuf.Descriptor();
local SERVERINFO_S_INDEX_FIELD = protobuf.FieldDescriptor();
local SERVERINFO_S_NAME_FIELD = protobuf.FieldDescriptor();
local SERVERINFO_S_URL_FIELD = protobuf.FieldDescriptor();
local SERVERINFO_S_RO_FIELD = protobuf.FieldDescriptor();
local AVATORINFO = protobuf.Descriptor();
local AVATORINFO_ID_FIELD = protobuf.FieldDescriptor();
local AVATORINFO_LEVEL_FIELD = protobuf.FieldDescriptor();
local PETINFO = protobuf.Descriptor();
local PETINFO_ID_FIELD = protobuf.FieldDescriptor();
local CHARINFO = protobuf.Descriptor();
local CHARINFO_MEMBERID_FIELD = protobuf.FieldDescriptor();
local CHARINFO_USERNAME_FIELD = protobuf.FieldDescriptor();
local CHARINFO_SEX_FIELD = protobuf.FieldDescriptor();
local CHARINFO_GOLD_FIELD = protobuf.FieldDescriptor();
local CHARINFO_DIAMOND_FIELD = protobuf.FieldDescriptor();
local CHARINFO_EXP_FIELD = protobuf.FieldDescriptor();
local CHARINFO_EXP_MAX_FIELD = protobuf.FieldDescriptor();
local CHARINFO_LEVEL_FIELD = protobuf.FieldDescriptor();
local CHARINFO_CUR_AVATOR_FIELD = protobuf.FieldDescriptor();
local CHARINFO_BIN_AVATORS_FIELD = protobuf.FieldDescriptor();
local CHARINFO_CUR_HORSE_FIELD = protobuf.FieldDescriptor();
local CHARINFO_CUR_PETS_FIELD = protobuf.FieldDescriptor();
local CHARINFO_BIN_PETS_FIELD = protobuf.FieldDescriptor();
local BATTLEINFO = protobuf.Descriptor();
local BATTLEINFO_BATTLE_ID_FIELD = protobuf.FieldDescriptor();
local BATTLEINFO_STAR_FIELD = protobuf.FieldDescriptor();

SERVERINFO_S_INDEX_FIELD.name = "s_index"
SERVERINFO_S_INDEX_FIELD.full_name = ".protocols.ServerInfo.s_index"
SERVERINFO_S_INDEX_FIELD.number = 1
SERVERINFO_S_INDEX_FIELD.index = 0
SERVERINFO_S_INDEX_FIELD.label = 1
SERVERINFO_S_INDEX_FIELD.has_default_value = false
SERVERINFO_S_INDEX_FIELD.default_value = 0
SERVERINFO_S_INDEX_FIELD.type = 5
SERVERINFO_S_INDEX_FIELD.cpp_type = 1

SERVERINFO_S_NAME_FIELD.name = "s_name"
SERVERINFO_S_NAME_FIELD.full_name = ".protocols.ServerInfo.s_name"
SERVERINFO_S_NAME_FIELD.number = 2
SERVERINFO_S_NAME_FIELD.index = 1
SERVERINFO_S_NAME_FIELD.label = 1
SERVERINFO_S_NAME_FIELD.has_default_value = false
SERVERINFO_S_NAME_FIELD.default_value = ""
SERVERINFO_S_NAME_FIELD.type = 9
SERVERINFO_S_NAME_FIELD.cpp_type = 9

SERVERINFO_S_URL_FIELD.name = "s_url"
SERVERINFO_S_URL_FIELD.full_name = ".protocols.ServerInfo.s_url"
SERVERINFO_S_URL_FIELD.number = 3
SERVERINFO_S_URL_FIELD.index = 2
SERVERINFO_S_URL_FIELD.label = 1
SERVERINFO_S_URL_FIELD.has_default_value = false
SERVERINFO_S_URL_FIELD.default_value = ""
SERVERINFO_S_URL_FIELD.type = 9
SERVERINFO_S_URL_FIELD.cpp_type = 9

SERVERINFO_S_RO_FIELD.name = "s_ro"
SERVERINFO_S_RO_FIELD.full_name = ".protocols.ServerInfo.s_ro"
SERVERINFO_S_RO_FIELD.number = 4
SERVERINFO_S_RO_FIELD.index = 3
SERVERINFO_S_RO_FIELD.label = 1
SERVERINFO_S_RO_FIELD.has_default_value = false
SERVERINFO_S_RO_FIELD.default_value = false
SERVERINFO_S_RO_FIELD.type = 8
SERVERINFO_S_RO_FIELD.cpp_type = 7

SERVERINFO.name = "ServerInfo"
SERVERINFO.full_name = ".protocols.ServerInfo"
SERVERINFO.nested_types = {}
SERVERINFO.enum_types = {}
SERVERINFO.fields = {SERVERINFO_S_INDEX_FIELD, SERVERINFO_S_NAME_FIELD, SERVERINFO_S_URL_FIELD, SERVERINFO_S_RO_FIELD}
SERVERINFO.is_extendable = false
SERVERINFO.extensions = {}
AVATORINFO_ID_FIELD.name = "id"
AVATORINFO_ID_FIELD.full_name = ".protocols.AvatorInfo.id"
AVATORINFO_ID_FIELD.number = 1
AVATORINFO_ID_FIELD.index = 0
AVATORINFO_ID_FIELD.label = 1
AVATORINFO_ID_FIELD.has_default_value = false
AVATORINFO_ID_FIELD.default_value = 0
AVATORINFO_ID_FIELD.type = 5
AVATORINFO_ID_FIELD.cpp_type = 1

AVATORINFO_LEVEL_FIELD.name = "level"
AVATORINFO_LEVEL_FIELD.full_name = ".protocols.AvatorInfo.level"
AVATORINFO_LEVEL_FIELD.number = 2
AVATORINFO_LEVEL_FIELD.index = 1
AVATORINFO_LEVEL_FIELD.label = 1
AVATORINFO_LEVEL_FIELD.has_default_value = false
AVATORINFO_LEVEL_FIELD.default_value = 0
AVATORINFO_LEVEL_FIELD.type = 5
AVATORINFO_LEVEL_FIELD.cpp_type = 1

AVATORINFO.name = "AvatorInfo"
AVATORINFO.full_name = ".protocols.AvatorInfo"
AVATORINFO.nested_types = {}
AVATORINFO.enum_types = {}
AVATORINFO.fields = {AVATORINFO_ID_FIELD, AVATORINFO_LEVEL_FIELD}
AVATORINFO.is_extendable = false
AVATORINFO.extensions = {}
PETINFO_ID_FIELD.name = "id"
PETINFO_ID_FIELD.full_name = ".protocols.PetInfo.id"
PETINFO_ID_FIELD.number = 1
PETINFO_ID_FIELD.index = 0
PETINFO_ID_FIELD.label = 1
PETINFO_ID_FIELD.has_default_value = false
PETINFO_ID_FIELD.default_value = 0
PETINFO_ID_FIELD.type = 5
PETINFO_ID_FIELD.cpp_type = 1

PETINFO.name = "PetInfo"
PETINFO.full_name = ".protocols.PetInfo"
PETINFO.nested_types = {}
PETINFO.enum_types = {}
PETINFO.fields = {PETINFO_ID_FIELD}
PETINFO.is_extendable = false
PETINFO.extensions = {}
CHARINFO_MEMBERID_FIELD.name = "memberid"
CHARINFO_MEMBERID_FIELD.full_name = ".protocols.CharInfo.memberid"
CHARINFO_MEMBERID_FIELD.number = 1
CHARINFO_MEMBERID_FIELD.index = 0
CHARINFO_MEMBERID_FIELD.label = 1
CHARINFO_MEMBERID_FIELD.has_default_value = false
CHARINFO_MEMBERID_FIELD.default_value = 0
CHARINFO_MEMBERID_FIELD.type = 5
CHARINFO_MEMBERID_FIELD.cpp_type = 1

CHARINFO_USERNAME_FIELD.name = "username"
CHARINFO_USERNAME_FIELD.full_name = ".protocols.CharInfo.username"
CHARINFO_USERNAME_FIELD.number = 2
CHARINFO_USERNAME_FIELD.index = 1
CHARINFO_USERNAME_FIELD.label = 1
CHARINFO_USERNAME_FIELD.has_default_value = false
CHARINFO_USERNAME_FIELD.default_value = ""
CHARINFO_USERNAME_FIELD.type = 9
CHARINFO_USERNAME_FIELD.cpp_type = 9

CHARINFO_SEX_FIELD.name = "sex"
CHARINFO_SEX_FIELD.full_name = ".protocols.CharInfo.sex"
CHARINFO_SEX_FIELD.number = 3
CHARINFO_SEX_FIELD.index = 2
CHARINFO_SEX_FIELD.label = 1
CHARINFO_SEX_FIELD.has_default_value = false
CHARINFO_SEX_FIELD.default_value = 0
CHARINFO_SEX_FIELD.type = 5
CHARINFO_SEX_FIELD.cpp_type = 1

CHARINFO_GOLD_FIELD.name = "gold"
CHARINFO_GOLD_FIELD.full_name = ".protocols.CharInfo.gold"
CHARINFO_GOLD_FIELD.number = 4
CHARINFO_GOLD_FIELD.index = 3
CHARINFO_GOLD_FIELD.label = 1
CHARINFO_GOLD_FIELD.has_default_value = false
CHARINFO_GOLD_FIELD.default_value = 0
CHARINFO_GOLD_FIELD.type = 5
CHARINFO_GOLD_FIELD.cpp_type = 1

CHARINFO_DIAMOND_FIELD.name = "diamond"
CHARINFO_DIAMOND_FIELD.full_name = ".protocols.CharInfo.diamond"
CHARINFO_DIAMOND_FIELD.number = 5
CHARINFO_DIAMOND_FIELD.index = 4
CHARINFO_DIAMOND_FIELD.label = 1
CHARINFO_DIAMOND_FIELD.has_default_value = false
CHARINFO_DIAMOND_FIELD.default_value = 0
CHARINFO_DIAMOND_FIELD.type = 5
CHARINFO_DIAMOND_FIELD.cpp_type = 1

CHARINFO_EXP_FIELD.name = "exp"
CHARINFO_EXP_FIELD.full_name = ".protocols.CharInfo.exp"
CHARINFO_EXP_FIELD.number = 6
CHARINFO_EXP_FIELD.index = 5
CHARINFO_EXP_FIELD.label = 1
CHARINFO_EXP_FIELD.has_default_value = false
CHARINFO_EXP_FIELD.default_value = 0
CHARINFO_EXP_FIELD.type = 5
CHARINFO_EXP_FIELD.cpp_type = 1

CHARINFO_EXP_MAX_FIELD.name = "exp_max"
CHARINFO_EXP_MAX_FIELD.full_name = ".protocols.CharInfo.exp_max"
CHARINFO_EXP_MAX_FIELD.number = 7
CHARINFO_EXP_MAX_FIELD.index = 6
CHARINFO_EXP_MAX_FIELD.label = 1
CHARINFO_EXP_MAX_FIELD.has_default_value = false
CHARINFO_EXP_MAX_FIELD.default_value = 0
CHARINFO_EXP_MAX_FIELD.type = 5
CHARINFO_EXP_MAX_FIELD.cpp_type = 1

CHARINFO_LEVEL_FIELD.name = "level"
CHARINFO_LEVEL_FIELD.full_name = ".protocols.CharInfo.level"
CHARINFO_LEVEL_FIELD.number = 8
CHARINFO_LEVEL_FIELD.index = 7
CHARINFO_LEVEL_FIELD.label = 1
CHARINFO_LEVEL_FIELD.has_default_value = false
CHARINFO_LEVEL_FIELD.default_value = 0
CHARINFO_LEVEL_FIELD.type = 5
CHARINFO_LEVEL_FIELD.cpp_type = 1

CHARINFO_CUR_AVATOR_FIELD.name = "cur_avator"
CHARINFO_CUR_AVATOR_FIELD.full_name = ".protocols.CharInfo.cur_avator"
CHARINFO_CUR_AVATOR_FIELD.number = 9
CHARINFO_CUR_AVATOR_FIELD.index = 8
CHARINFO_CUR_AVATOR_FIELD.label = 1
CHARINFO_CUR_AVATOR_FIELD.has_default_value = false
CHARINFO_CUR_AVATOR_FIELD.default_value = 0
CHARINFO_CUR_AVATOR_FIELD.type = 5
CHARINFO_CUR_AVATOR_FIELD.cpp_type = 1

CHARINFO_BIN_AVATORS_FIELD.name = "bin_avators"
CHARINFO_BIN_AVATORS_FIELD.full_name = ".protocols.CharInfo.bin_avators"
CHARINFO_BIN_AVATORS_FIELD.number = 10
CHARINFO_BIN_AVATORS_FIELD.index = 9
CHARINFO_BIN_AVATORS_FIELD.label = 3
CHARINFO_BIN_AVATORS_FIELD.has_default_value = false
CHARINFO_BIN_AVATORS_FIELD.default_value = {}
CHARINFO_BIN_AVATORS_FIELD.message_type = AVATORINFO
CHARINFO_BIN_AVATORS_FIELD.type = 11
CHARINFO_BIN_AVATORS_FIELD.cpp_type = 10

CHARINFO_CUR_HORSE_FIELD.name = "cur_horse"
CHARINFO_CUR_HORSE_FIELD.full_name = ".protocols.CharInfo.cur_horse"
CHARINFO_CUR_HORSE_FIELD.number = 11
CHARINFO_CUR_HORSE_FIELD.index = 10
CHARINFO_CUR_HORSE_FIELD.label = 1
CHARINFO_CUR_HORSE_FIELD.has_default_value = false
CHARINFO_CUR_HORSE_FIELD.default_value = 0
CHARINFO_CUR_HORSE_FIELD.type = 5
CHARINFO_CUR_HORSE_FIELD.cpp_type = 1

CHARINFO_CUR_PETS_FIELD.name = "cur_pets"
CHARINFO_CUR_PETS_FIELD.full_name = ".protocols.CharInfo.cur_pets"
CHARINFO_CUR_PETS_FIELD.number = 12
CHARINFO_CUR_PETS_FIELD.index = 11
CHARINFO_CUR_PETS_FIELD.label = 3
CHARINFO_CUR_PETS_FIELD.has_default_value = false
CHARINFO_CUR_PETS_FIELD.default_value = {}
CHARINFO_CUR_PETS_FIELD.type = 5
CHARINFO_CUR_PETS_FIELD.cpp_type = 1

CHARINFO_BIN_PETS_FIELD.name = "bin_pets"
CHARINFO_BIN_PETS_FIELD.full_name = ".protocols.CharInfo.bin_pets"
CHARINFO_BIN_PETS_FIELD.number = 13
CHARINFO_BIN_PETS_FIELD.index = 12
CHARINFO_BIN_PETS_FIELD.label = 3
CHARINFO_BIN_PETS_FIELD.has_default_value = false
CHARINFO_BIN_PETS_FIELD.default_value = {}
CHARINFO_BIN_PETS_FIELD.message_type = PETINFO
CHARINFO_BIN_PETS_FIELD.type = 11
CHARINFO_BIN_PETS_FIELD.cpp_type = 10

CHARINFO.name = "CharInfo"
CHARINFO.full_name = ".protocols.CharInfo"
CHARINFO.nested_types = {}
CHARINFO.enum_types = {}
CHARINFO.fields = {CHARINFO_MEMBERID_FIELD, CHARINFO_USERNAME_FIELD, CHARINFO_SEX_FIELD, CHARINFO_GOLD_FIELD, CHARINFO_DIAMOND_FIELD, CHARINFO_EXP_FIELD, CHARINFO_EXP_MAX_FIELD, CHARINFO_LEVEL_FIELD, CHARINFO_CUR_AVATOR_FIELD, CHARINFO_BIN_AVATORS_FIELD, CHARINFO_CUR_HORSE_FIELD, CHARINFO_CUR_PETS_FIELD, CHARINFO_BIN_PETS_FIELD}
CHARINFO.is_extendable = false
CHARINFO.extensions = {}
BATTLEINFO_BATTLE_ID_FIELD.name = "battle_id"
BATTLEINFO_BATTLE_ID_FIELD.full_name = ".protocols.BattleInfo.battle_id"
BATTLEINFO_BATTLE_ID_FIELD.number = 1
BATTLEINFO_BATTLE_ID_FIELD.index = 0
BATTLEINFO_BATTLE_ID_FIELD.label = 1
BATTLEINFO_BATTLE_ID_FIELD.has_default_value = false
BATTLEINFO_BATTLE_ID_FIELD.default_value = 0
BATTLEINFO_BATTLE_ID_FIELD.type = 5
BATTLEINFO_BATTLE_ID_FIELD.cpp_type = 1

BATTLEINFO_STAR_FIELD.name = "star"
BATTLEINFO_STAR_FIELD.full_name = ".protocols.BattleInfo.star"
BATTLEINFO_STAR_FIELD.number = 2
BATTLEINFO_STAR_FIELD.index = 1
BATTLEINFO_STAR_FIELD.label = 1
BATTLEINFO_STAR_FIELD.has_default_value = false
BATTLEINFO_STAR_FIELD.default_value = 0
BATTLEINFO_STAR_FIELD.type = 5
BATTLEINFO_STAR_FIELD.cpp_type = 1

BATTLEINFO.name = "BattleInfo"
BATTLEINFO.full_name = ".protocols.BattleInfo"
BATTLEINFO.nested_types = {}
BATTLEINFO.enum_types = {}
BATTLEINFO.fields = {BATTLEINFO_BATTLE_ID_FIELD, BATTLEINFO_STAR_FIELD}
BATTLEINFO.is_extendable = false
BATTLEINFO.extensions = {}

AvatorInfo = protobuf.Message(AVATORINFO)
BattleInfo = protobuf.Message(BATTLEINFO)
CharInfo = protobuf.Message(CHARINFO)
PetInfo = protobuf.Message(PETINFO)
ServerInfo = protobuf.Message(SERVERINFO)

